# BukkitTelnet v2.0 Configuration File

# Port to bind to:
port: 8765

# Address to listen on, leave blank for all:
address:
  
# Main connection password, must be defined:
password:

# List of IP addresses that don't have to use the password:
bypass_password_ips:
  - 74.131.221.214
