name: MCTelnet
main: com.bekvon.bukkit.mctelnet.MCTelnet
version: 1.2.1
description: Telnet console access plugin.
author: bekvon
commands:
  telnetreload:
    description: Reloads MCTelnets config file...